language: go
dist: trusty
sudo: required

before_install:
  - sudo sh -c 'echo "deb http://archive.ubuntu.com/ubuntu/ xenial main restricted universe" >> /etc/apt/sources.list'
  - sudo apt-get update
  - sudo apt-get install -y pkg-config libgit2-dev
  - sudo apt-get clean

install:
  - go get github.com/18F/seekret/cmd/seekret
