version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.8

    working_directory: /go/src/github.com/18F/seekret

    steps:
      - checkout
      - run: sudo sh -c 'echo "deb http://ftp.us.debian.org/debian/ unstable main contrib non-free" >> /etc/apt/sources.list'
      - run: sudo apt-get update -qq
      - run: sudo apt-get install -y pkg-config
      - run: sudo apt-get -t unstable install -y libgit2-dev
      - run: sudo apt-get remove --purge libgnutls-deb0-28
      - run: sudo apt-get autoremove
      - run: sudo apt-get clean
      - run: go get github.com/18F/seekret/cmd/seekret
